### ISSUE TITLE
Extension Disabled on MS Edge Due to Frequent Reloads & Some Friendly Suggestion

### ISSUE THREAD

**Issue by Zujaj** [alganzory/HaramBlur#100]
### السلام علیکم ورحمتہ اللہ وبرکاتہ

@alganzory JazakAllah, I have been seeking such a solution for quite some time. May ALLAH PAK bless you for your hard efforts. Regarding feedback, I would like to report one issue and share a suggestion as well.

## Issue: Extension Gets Disabled on MS Edge

- Yesterday, I installed this extension from the Chrome extension web page.
- Refreshed all pages as prompted by the extension.
- Edge has disabled the extension as it complains that this extension reloads itself too frequently.
![image](https://github.com/user-attachments/assets/5edf3ed6-bffe-47b6-a250-b76cc79ca89a)

### Device Specifications
- Laptop: Dell Vostro 5620 12th Gen Intel(R) Core(TM) i7-1260P  2.10 GH | 16GB RAM | 929GB SSD (1 TB)
- OS: Windows 11 Pro version 23H2 with the latest updates
- Browser: MS Edge Version 129.0.2792.52 (Official Build) (64-bit)
- No of tabs opened: More than 10

## Suggestion

For better scalability of this project, utilize Typescript over Javascript as it offers:

1. **Static Typing:** TypeScript adds static types to JavaScript, allowing you to define the types of variables, function parameters, and return values. This helps catch errors early in the development process, making the code more reliable and easier to debug.

2. **Improved Tooling:** TypeScript offers better tooling support, including autocompletion, navigation, and refactoring tools. This makes it easier to manage and maintain large codebases, especially when working in teams.

3. **Enhanced Code Quality**: With TypeScript, you can enforce consistent coding practices and reduce the likelihood of runtime errors. This leads to cleaner, more maintainable code, which is crucial for scaling projects.

4. **Better Documentation:** Type annotations in TypeScript serve as a form of documentation, making it easier for developers to understand the codebase. This is particularly useful when new developers join the project or when revisiting code after some time.

5. **Compatibility:** TypeScript is a superset of JavaScript, meaning you can gradually introduce it into an existing JavaScript project. This allows for a smooth transition without needing to rewrite the entire codebase.

6. **Browser Compatibility:** TypeScript can help ensure that your Chrome extension works consistently across different versions of Chrome and other Chromium-based browsers by catching potential issues early.

**Comment by alganzory** [comment]
This issue has been solved with the recent updates, 
thanks for the suggestions, it's quite hard for me to do the typescript migration atm but will consider soon
