### ISSUE TITLE
Extension doesn't work for me in firefox and very memory consuming

### ISSUE THREAD

**Issue by ahmadmourad** [alganzory/HaramBlur#102]
I tried to use the extension on firefox it doesn't blur anything in all websites, I tried to uninstall and reinstalling it to my browser and nothing happend. After that I tried it on chromium it worked normally. 

The extension is very memory consuming always makes memory consumption over 90% of 16gb ram specially when loading any images

**Comment by alganzory** [comment]
what versions do you have installed?

**Comment by ahmadmourad** [comment]
> what versions do you have installed?

Mozilla Firefox 131.0
Haram blur Version 0.2.1

**Comment by OsamaNabih** [comment]
I can confirm the memory issues. It is completely maxing out my 16GB system (Firefox consuming over 10Gigs with a single video tab playing)
I tried to make the extension not work for videos, but it didn't matter, the memory keeps growing at 100MB+ per second.
Only workaround was disabling it for the website, which beats the purpose.

But the extension itself was working fine for me and actually blurring stuff.
Versions
Firefox 131.0.3 
Haram Blur Version 0.2.1

**Comment by OsamaNabih** [comment]
For me this was for websites with lots of images and videos.
The worst example is Youtube
But opening up a `Booking.com` home tab (not even a pictures one) consumes like 3 GBs of RAM

**Comment by alganzory** [comment]
Yes there's a problem in Firefox version, I should update it to match
chrome, thanks for the investigations
