### ISSUE TITLE
It takes split seconds before activating the blur overlay!

### ISSUE THREAD

**Issue by imnotadev-ineedhelp** [alganzory/HaramBlur#106]
I can see there are already tons of [issues](https://github.com/alganzory/HaramBlur/issues). But I think it is important. So, it needs to be addressed. In this [video](https://youtu.be/P5mD1jRPX3E), you will see that when the woman comes into the frame, it takes split seconds before activating the blur in **both blur modes**. The same thing happened to me in many many videos. I will add them in the future if I find them again.

**Comment by alganzory** [comment]
Do you mean the initial seconds of the video don't get processed immediately?

**Comment by imnotadev-ineedhelp** [comment]
No, I meant let's say a woman came to the frame of a video; it shows the woman for 0.5-1.5 seconds then blurs her. [Here](https://github.com/user-attachments/assets/eeacb388-8238-4a2c-ab29-4a0847298993) you can see she is not blurry but just after 0.5 seconds [she](https://github.com/user-attachments/assets/2033cd7b-6351-41c4-9065-d5ec4fd87580) is halal again :)

**Comment by mr1lazycoder** [comment]
the blur is slow to take effect anyway in videos. whenever a frame changes and there's a female it either doesn't blur her immediatly if it's a long scene or if its a short scene the blur is applied on other subjects although not females. This is on firefox 
Version  132.0 and haramBlur version 0.2.2

**Comment by bthnakkurt** [comment]
you must stop living in your dream world. if you dont want to see normal women, then just go back to cave age.

**Comment by mr1lazycoder** [comment]
You need to learn good manners. The point of the extension is to not see
women and probably there must be a way to speed up the process of blurring.
Lowering one's gaze is commanded by allah and has many rewards it's not
just a wishful dream.
