### ISSUE TITLE
Fix controls on videos 

### ISSUE THREAD

**Issue by HussainElemam** [alganzory/HaramBlur#107]
In some social media platform such as X and Instagram when a video get blur it this prevent user from accessing the controls on the video (pause, continue, volume controls, and so on) and it is very annoying specially when the video is muted by default and you want to unmute it.
The solution is simple, I have tried it on the browser and it works, just add `pointer-events: none;` to the `hb-wrapper` (I don't know if this would effect other features but it works in my case)

**Comment by alganzory** [comment]
Thank you for the suggestion, will fix

**Comment by HussainElemam** [comment]
One thing I noticed - if it will help you somehow - that the problem only happens when using Specific Blur, when using Whole Blur the controls works fine
