### ISSUE TITLE
Video blur performance improvements

### ISSUE THREAD

**Issue by man2machine** [alganzory/HaramBlur#11]
Assalamu alaikum,

Here is a suggestion for the video blurring:
When you take the video frames and process it in the detector, if it needs to be blurred, set it to blur for at least 2 seconds. This will avoid any scenarios where the video flickers in and out when sometimes there are false negatives and improve the performance in shaa Allah. That means after it blurs the video, even if in a subsequent frame it detects nothing to blur, it will still continue to have the video blurred as it is within the 2 seconds. Hope this makes sense!

Jazak Allahu Khair.

**Comment by alganzory** [comment]
Walaikum Assalam, 

I have considered doing this but the issue with this delay is the false positives, in the version 0.0.2 I am trying another model for the face detection that should hopefully reduce the flickering false negatives, I will also experiment with this idea but maybe with something less than 2 seconds. 

I appreciate your continuous feedback and suggestions, Jazak Allahu Khairan 

Thank you for your continous feedback and suggestions,
