### ISSUE TITLE
Problem with google drive pdfs.

### ISSUE THREAD

**Issue by TheBombh2** [alganzory/HaramBlur#18]
For some reason whenever the extension is enabled no pdfs on google drives loads.
it all shows like this:

![image](https://github.com/alganzory/HaramBlur/assets/62998842/33352f3b-8aae-4fe1-8f2a-8ebc57de3716)

To reproduce just open any pdf on google drive.

**Comment by TheBombh2** [comment]
Sure thing. Great work so far on the project and good luck.

**Comment by alganzory** [comment]
@TheBombh2 this should be resolved with 0.1.6
