### ISSUE TITLE
Rethink blurry start mode

### ISSUE THREAD

**Issue by alganzory** [alganzory/HaramBlur#26]
Users don't seem to like blurry start mode because they don't understand why images blur then go unblurred,
The whole point of blurry start is to avoid seeing the undesirable content briefly before it gets detected, but it seems I need to either make it more understandable to the user or get rid of it entirely by enhancing the speed of detection..

**Comment by man2machine** [comment]
I believe I made this suggestion earlier in one of the issues in the repo. I do find it a useful feature, but perhaps you can try making it off by default, replace it with a loading symbol rather than a blurry image, make the description more understandable, or something like that.
