### ISSUE TITLE
Google Meet is always blurred

### ISSUE THREAD

**Issue by mahmouds12** [alganzory/HaramBlur#37]
When I have google meet meetings, the screen is always blurred, and I have to disable the extension to unblur it.

Check this: 
![image](https://github.com/alganzory/HaramBlur/assets/15720804/84e30eab-623e-4164-b035-b55bce235f8b)

Here are my enabled settings for reference:
```
Blur Media on Load: true
Blur amount: 10px
Strictness: 10%
Media to Blur: [images, videos]
Faces to Blur: [female]
Unblur on hover: [images, videos]
```

**Comment by alganzory** [comment]
Hi @mahmouds12 , thanks for reporting this, version 0.1.3 just got released a couple of hours ago, I suspect it solves this, can you please let me know if it still happens?

**Comment by mahmouds12** [comment]
@alganzory Thanks for your fast response, will check in the next google meeting and let you know.

**Comment by mahmouds12** [comment]
Hi @alganzory 
I think this one is solved, now it blurs only for a few seconds then it gets unblurred
