### ISSUE TITLE
Linkedin doesn't load with Haram Blur enabled

### ISSUE THREAD

**Issue by mahmouds12** [alganzory/HaramBlur#39]
I've encountered an issue where LinkedIn doesn't consistently load when the HaramBlur extension is enabled. Instead, it remains stuck on the splash screen indefinitely. You can see an example of the issue in this screenshot: HaramBlur Issue
![image](https://github.com/alganzory/HaramBlur/assets/15720804/e71a9ea0-4f69-4427-a3e3-b36e791ee3cc)

Interestingly, when I disable the extension and refresh the page, LinkedIn loads normally. 
I'm currently using version 0.1.5 of the extension. It's worth noting that this issue doesn't occur consistently, making it a bit challenging to troubleshoot.

**Comment by alganzory** [comment]
Hi Mahmoud, Thank you for continuing to support this project, really appreciate it dude.
As for the issue you reported, I can't imagine how this extension could be causing it, it's also not happening on my machine, can you try the extension in incognito mode to make sure it's not cause by other extensions and maybe make sure your internet connection is stable?

**Comment by mahmouds12** [comment]
I just tried it now again with the extension disabled, it worked. Then I enabled the extension and tried to open this [link ](https://www.linkedin.com/in/mohamed-alganzory-853198217/?originalSubdomain=my) again, and it's stuck on Linkedin splash screen.

**Comment by alganzory** [comment]
I am not sure why it happens for you, I'll look into it though.
On a side note, how did you find that account lmao, this is[ my linkedin profile ](https://www.linkedin.com/in/alganzory/)

**Comment by mahmouds12** [comment]
Lool, I just googled and that what comes first :D
Here's a screen recording for the issue:

https://github.com/alganzory/HaramBlur/assets/15720804/eba3484e-0522-4ac9-9b10-9c1af1f21c2e

**Comment by mahmouds12** [comment]
Lool, I just googled your name with linkedin and that what comes first :D
Here's a screen recording for the issue:

https://github.com/alganzory/HaramBlur/assets/15720804/c8dac708-e0c8-4243-a6cc-681c52d46c62

**Comment by alganzory** [comment]
> Lool, I just googled your name with linkedin and that what comes first :D Here's a screen recording for the issue:
> 
>  Recording.2023-11-22.223954.1.mp4

Thank you for your effort, I think I may have an idea why it happens, I will look into fixing it in the next version coming in a couple of days inshallah
