### ISSUE TITLE
similar plugin

### ISSUE THREAD

**Issue by marwenbk** [alganzory/HaramBlur#40]
i just came across NSFW 
https://github.com/nsfw-filter/nsfw-filter

**Comment by alganzory** [comment]
I am aware of the existence of that extension and other nsfw filters. In fact, HaramBlur uses the same nsfw detection model as that extension but also uses gender recognition models. Similarities aside, there are a few differences:
- HaramBlur is tailored for Muslims and to be more Shariah compliant, it's not just a NSFW filter, it also works for both genders.
- HaramBlur works on videos, others don't 
- The long term plan of HaramBlur is to produce dedicated shariah-compliant ai model, cover more platforms, continue to support muslims specifically. 

This project might not be as mature or performant as that one just yet, but that will happen soon enough inshallah.
