### ISSUE TITLE
BUG: NSFW detection does not detect on Kiwi Browser

### ISSUE THREAD

**Issue by LinuxJava7** [alganzory/HaramBlur#49]
My settings:
- Extension is on
- Blur media on load, on
- Blur amount, 30px
- Greyscale, off
- Strictness, 100%
- Media to blur, images and videos
- Faces to blur, female
- Unblur on hover, disabled

Android 13, Kiwi Browser 120.0.6099.26

It blurs all the media on load, but unblurs all images after a bit.
The same website images are blurred on desktop (Chromium and Firefox)
My guess is that there is an issue with the detection, because the image is blurred on load

**Comment by man2machine** [comment]
I have been using it on Kiwi Browser and I get slightly different behavior, as in even if I choose blur on load, it doesn't start with the images blurred. However, after a second or two, it does blur the images correctly.

**Comment by alganzory** [comment]
somehow, the NSFW model doesn't work on kiwi, but the face detection works fine
