### ISSUE TITLE
Incorrect License Information on Mozilla Addons Website

### ISSUE THREAD

**Issue by RasheedAZ** [alganzory/HaramBlur#50]
Jazaakallaahu khairan for creating this useful extension brother. On the Mozilla Addons page, it does not mention that the addons is licensed under AGPL-3.0 which could deter many people from using it.

https://addons.mozilla.org/en-US/firefox/addon/haramblur/

Would be great if you could update that. Thanks.

**Comment by alganzory** [comment]
Thanks for the heads up, I changed it
