### ISSUE TITLE
Add documentation for Firefox extension

### ISSUE THREAD

**Issue by LinuxJava7** [alganzory/HaramBlur#54]
Right now, only the Chrome extension is in the README.MD file, documentation should be added about the Firefox extension as well.

**Comment by alganzory** [comment]
@LinuxJava7 thanks for pointing that out, I wanna add a note to the readme that the firefox branch is firefox-main and add both download links, I see your fork already has some work on it, you think you can raise a PR?

**Comment by LinuxJava7** [comment]
Sure
Are the build instructions the same for Firefox?

**Comment by alganzory** [comment]
yeah I don't think there's a difference, just a difference in uploading the extension to firefox, so in the readme of firefox-main I will have that  a little different
