### ISSUE TITLE
GPU inferencing on Nvidia cards?

### ISSUE THREAD

**Issue by ijnrghjkdsmigywneig203** [alganzory/HaramBlur#66]
Asslamu Alikum

Is this feature available? I have also noticed there are a lot of false negatives, it would be better to just find any woman on the screen and blur it immediately.

Baarak'Allahu Feekum for this ya Akhi.

**Comment by alganzory** [comment]
Walaikum Asalam, 

Yes the extension does have the features you mentioned, try lowering/increasing the strictness, I am working to improve the accuracy inshallah. 

Barak Allahu Feek
