### ISSUE TITLE
Models run local (on browser) or on server ???

### ISSUE THREAD

**Issue by shimaamorsy** [alganzory/HaramBlur#68]
Does the model used for human detection run locally within the browser or on the server ?

**Comment by alganzory** [comment]
locally within the browser

**Comment by shimaamorsy** [comment]
Which technique did you use to run the model on the browser?

**Comment by alganzory** [comment]
Please look into `src/offscreen.js` and `src/modules/detection.js` to understand how the models are loaded and used

**Comment by shimaamorsy** [comment]
السلام عليكم
بشمهندس ممكن اطلب من حضرتك مساعدة ؟
عايزين حضرتك تساعدنا في فهم بعض الاجزاء من اكواد ال HaramBlur فا لو ممكن
حضرتك تدخل معنا ميتنج انا والتيم بتاعي (زميلة اخري فقط) وان شاء الله مش
هنطول عل حضرتك ؟
