### ISSUE TITLE
Incompatibility with Certain Websites on Firefox Linux

### ISSUE THREAD

**Issue by arrahhal** [alganzory/HaramBlur#75]
After installing the plugin, some websites, such as codeforces.com, fail to load properly on Firefox (Linux). on Chrome every thing went well.

Steps:
- Disabled the plugin, and the websites returned to normal functionality.
- Tested the plugin in Chrome, and it worked without any issues.
- Tried the plugin in Firefox's private mode (with no other pluing), but the issue persisted.

![output](https://github.com/alganzory/HaramBlur/assets/114484556/cecc45e0-c694-415d-a174-3a3a021991c1)

I'm unsure if its a browser settings or the compatibility with the Firefox version plugin problem.

**Comment by arrahhal** [comment]
same thing on Firefox/Windows

**Comment by alganzory** [comment]
@arrahhal Thank you for filing this, honestly I should get to updating firefox version to match chrome's. Will fix soon inshallah

**Comment by arrahhal** [comment]
إن شاء الله

**Comment by alganzory** [comment]
I figured out the problem, some sites don't allow the iframe that the extension uses for video transfer, unfortunately this means I'd have to find a different technique that doesn't cause such problems, but for the time being you can use the newly added whitelist feature.. oh wait, that doesn't prevent the iframe creation, I forgot to do that in this update.. i'll push this one very soon inshallah so you can whitelist some sites and not have this issue

**Comment by arrahhal** [comment]
Why this only happen on Firefox,  doesn't Chrome version use the same technique?
