### ISSUE TITLE
create an id for your extension for gecko (firefox) based browsers in manifest.json

### ISSUE THREAD

**Issue by iamtalhaasghar** [alganzory/HaramBlur#79]
It would be owsm if you can add   the following snippet in your manifest.json.
```
"browser_specific_settings": {
    "gecko": {
      "id": "<some_id>",
          .....
    },
```

ublock's manifest.json, as an example:
https://github.com/gorhill/uBlock/blob/9146134874050ee50a11e25f31034a2416cf5988/platform/firefox/manifest.json#L19

## Why?
In firefox `policies.json` I can then `allow` or `force_install` this extension by its id in my sibling pc. I have only allowed a set of extension on his pc. Sample: https://github.com/mozilla/policy-templates/blob/8d2d6134b32ed9c88511eb75b06ec54dd10170a0/linux/policies.json#L131

**Comment by alganzory** [comment]
@iamtalhaasghar  don't I have that in manifest.json for firefox-main branch?

**Comment by iamtalhaasghar** [comment]
@alganzory Nope, 
![image](https://github.com/alganzory/HaramBlur/assets/46928648/ee910013-4f0b-4dac-97e3-b5f33121aced)

**Comment by iamtalhaasghar** [comment]
Using this firefox [extension](https://github.com/mkaply/queryamoid/releases/tag/v0.1), i was able to find id of your extension which is: `info@haramblur.com`

**Comment by alganzory** [comment]
@iamtalhaasghar 
https://github.com/alganzory/HaramBlur/blob/firefox-main/manifest.json#L26

But I'm glad you found it anyway, also thanks for sharing about the policy thingy I didn't even know since I don't use Firefox

**Comment by iamtalhaasghar** [comment]
firefox policies is a great tool to disable access to certain sites, disable installation of new add ons and allow only certain add-ons. Its a great hack!
