### ISSUE TITLE
Initially blurring content before detection

### ISSUE THREAD

**Issue by elfaidi-ghassen** [alganzory/HaramBlur#87]
السلام عليكم أخي
عندي فكرة، فالمشكلة أن الإضافة تتأخر حوالي ثانية حتى تقوم بالتعرف على محتوى صورة وتقوم بتغطيته
فأقترح لما لا تكون كل الصور مغطات من البداية ثم تعيد إضهارها إن كانت غير محرمة.
إن كان هذا سيفسد شكل المواقع فعلى الأقل في المواقع المشهورة ولو في أجزاء منها مثل social media feeds وصور profile pictures
وختاما، جزاك الله خيرا على صنع هذه الإضافة، فعلا مفيدة لكل مسلم، فبارك الله فيك.

**Comment by alganzory** [comment]
وعليكم السلام ورحمة الله وبركاته
الخاصية موجودة بالفعل يمكنك تفعيلها من الاعدادات
بارك الله فيكم
