### ISSUE TITLE
لا يتم تشويش الصور في بعض الأماكن في منصة لينكد ان

### ISSUE THREAD

**Issue by Ahmad-Nidal** [alganzory/HaramBlur#93]
السلام عليكم

لا يتم تشويش صورة الملف الشخصي على لينكد ان وكذلك الصورة الصغيرة عند إعادة النشر - Repost 

قمت بتفعيل تشويش صور الرجال وهذه صور توضح المشكلة:

![image](https://github.com/alganzory/HaramBlur/assets/79116096/cc488efd-05e4-414b-b3e8-edf7c20cfeba)

![image](https://github.com/alganzory/HaramBlur/assets/79116096/37910105-ee88-4bc1-8611-48572b3b02f6)

وكذلك من الملاحظ عدم تشويش كثير من الصور في صفحة mynetwork

مثلا حساب هذا الرجل: mohamed-tanash
لم يتم تشويش صورته في صفحة mynetwork لكن تم تشويشها في صفحة المنشورات
![Screenshot from 2024-06-14 22-41-05](https://github.com/alganzory/HaramBlur/assets/79116096/d0189523-b707-46e1-9be5-41114d3de31b)
![Screenshot from 2024-06-14 22-41-15](https://github.com/alganzory/HaramBlur/assets/79116096/929c1eeb-364e-4bd6-a269-06212203c6ce)

**Comment by alganzory** [comment]
وعليكم السلام ورحمة الله وبركاته 
شكرا ليك.. هشوف المشكلة ان شاء الله

**Comment by Ahmad-Nidal** [comment]
صور المنشورات في لينكد ان كذلك لا يتم تشويشها
