### ISSUE TITLE
Not an issue but a suggestion (Mobile App)

### ISSUE THREAD

**Issue by abdullahazmy** [alganzory/HaramBlur#95]
Hope if you can create a mobile app with the same idea, even if use Flutter or any cross-platform technology 
This is a great contribution, thanks for your efforts
May Allah accept.

**Comment by alganzory** [comment]
JazakAllahu Khairan, 
Thanks for the suggestion. It's unfortunately not as easy as it sounds, but it's in the plan inshallah
