### ISSUE TITLE
Youtube Music fails to load some podcasts with error Video unavailable

### ISSUE THREAD

**Issue by mohamedGamalAbuGalala** [alganzory/HaramBlur#96]
I was trying to play one episode from [(وعي) podcast](https://music.youtube.com/playlist?list=PLoifknR2YOZTYefKAT2ySfr7mjr7filmP) while having haramBlur on and it failed to load with error Video unavailable. also, a lot of other podcasts are not working. after disabling haramBlur it worked 👍🏼

**Comment by alganzory** [comment]
You can whitelist that domain in the settings of HaramBlur (by toggling this switch off) instead of turning it entirely off
![image](https://github.com/alganzory/HaramBlur/assets/59778310/bab301dd-e372-45aa-bfa4-b0ba80f34bcf)

I'll look into it, thanks for reporting

**Comment by mohamedGamalAbuGalala** [comment]
I can't open the extension on the page. so I can't disable it. I'm using the latest edge version on mac.

**Comment by mohamedGamalAbuGalala** [comment]
I believe the extension is not opening on all pages on edge.
